vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    image_event:
      uri_prefix: /images/Event
      upload_destination: "%kernel.project_dir%/public/img"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
